//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerprintAgent.Installer.Properties
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   Hand-authored to match VietnameseStrings.resx. SDK-style projects without
    ///   WinForms SDK do not auto-generate this file; manually maintained for
    ///   compile-time strongly-typed access from CustomActions.cs.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VietnameseStrings
    {

        private static System.Resources.ResourceManager _resourceManager;

        private static System.Globalization.CultureInfo _resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VietnameseStrings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(_resourceManager, null))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FingerprintAgent.Installer.Properties.VietnameseStrings", typeof(VietnameseStrings).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return _resourceCulture;
            }
            set
            {
                _resourceCulture = value;
            }
        }

        /// <summary>
        ///   Title for VC++ redistributable missing error dialog (D-11).
        /// </summary>
        internal static string VcRedistMissingTitle
        {
            get
            {
                return ResourceManager.GetString("VcRedistMissingTitle", _resourceCulture);
            }
        }

        /// <summary>
        ///   Body for VC++ redistributable missing error dialog. Includes download URL.
        /// </summary>
        internal static string VcRedistMissingBody
        {
            get
            {
                return ResourceManager.GetString("VcRedistMissingBody", _resourceCulture);
            }
        }

        /// <summary>
        ///   Body for scanner-not-detected success-with-warning dialog (D-38).
        /// </summary>
        internal static string ScannerNotDetectedBody
        {
            get
            {
                return ResourceManager.GetString("ScannerNotDetectedBody", _resourceCulture);
            }
        }

        /// <summary>
        ///   Success message after fresh install (D-39).
        /// </summary>
        internal static string InstallSuccessFresh
        {
            get
            {
                return ResourceManager.GetString("InstallSuccessFresh", _resourceCulture);
            }
        }

        /// <summary>
        ///   Success message after upgrade (D-39). Format: "Đã cập nhật lên phiên bản v{version}."
        /// </summary>
        internal static string InstallSuccessUpgrade
        {
            get
            {
                return ResourceManager.GetString("InstallSuccessUpgrade", _resourceCulture);
            }
        }

        /// <summary>
        ///   Generic error message shown when install fails for non-VC++ reasons (D-38).
        /// </summary>
        internal static string InstallGenericError
        {
            get
            {
                return ResourceManager.GetString("InstallGenericError", _resourceCulture);
            }
        }
    }
}
