<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>FingerprintAgent</RootNamespace>
    <AssemblyName>FingerprintAgent</AssemblyName>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FingerprintAgent\FingerprintAgent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
</Project>